### ISSUE TITLE
Run in detach mode

### ISSUE THREAD

**Issue by Uhsac** [kfei/docktorrent#11]
It would be cool if we could launch docktorrent in detach mode (-d in docker)

**Comment by CaptInsano** [comment]
I would also love this. At present I cannot run this container on my UnRaid server due to the lack of detach support.

My unRAID server tries to launch it with this command:

/usr/bin/docker run -d --name="docktorrent" --net="bridge" -e TZ="Europe/London" -p 8089:80/tcp -p 45566:45566/tcp -p 9527:9527/udp -v "/mnt/cache/Docker/AppData/rTorrent/":"/rtorrent":rw kfei/docktorrent

But it just crashes with this error:

/usr/bin/docker logs --tail=350 -f docktorrent 2>&1
Error opening terminal: unknown.

rTorrent exited.

Shutting down...

I would love to see this fixed

**Comment by Uhsac** [comment]
You can launch it with -t command if you want, it's not like detach but it works

**Comment by kfei** [comment]
:+1: 

Yes the support of running in detach mode is necessary. And I think running rTorrent inside `tmux` or `screen` is the only way since rTorrent itself doesn't run in background...

Accepting any pull request on this.

**Comment by ArmoredDragon** [comment]
Was this quietly fixed or something? Seems to work fine for me, I just ran it like this:

docker run -itd -p 80:80 -p 45566:45566 -p 9527:9527/udp --dns 192.168.1.1 -v /storage/:/storage kfei/docktorrent

Seems to detach just fine.

**Comment by kfei** [comment]
Hi @ArmoredDragon, `-itd` is just fine since the `t` allocates a tty for rTorrent to outputs.

**Comment by o6uoq** [comment]
If it's working fine, can this issue be closed? Seems to be working fine here, too.

**Comment by colthreepv** [comment]
bump, it would be very useful to not allocate a tty to use on docker-compose

using `tty: true` breaks logs big time :(

**Comment by o6uoq** [comment]
I think the nature of rtorrent requires a tty, as rtorrent itself doesn't have a `daemon` mode. When using rtorrent before Docker, I had to use `screen` to get around this.
