### ISSUE TITLE
port change

### ISSUE THREAD

**Issue by urbels** [kfei/docktorrent#24]
Hello!

If I want to change default ports on already compiled container. What steps should I do? I tried just to change them in launch parametres but I can`t access web ui not at 80 port not new one so something went wrong.

**Comment by kfei** [comment]
Hi @urbels,

Assuming you are going to use port 8000 instead of 80. Then the port mapping parameter should be:
`-p 8000:80` (The later 80 is container-side, should not be changed.)

**Comment by urbels** [comment]
80 change was the problem, thanks.

**Comment by urbels** [comment]
btw where to change rtorrent port? it ignores port I add on the launch instead using your default port.

**Comment by kfei** [comment]
In general, you don't have to change the port settings inside container. You can just change the **port mapping** for that container. Assuming you want all incoming traffic for rTorrent to go through port 12345 on the linux host, you can just pass `-p 12345:45566` for that to work.

**Comment by urbels** [comment]
Tried it and port still is 45566 anyway.

**Comment by kfei** [comment]
My bad!

In this case port mapping doesn't work since rTorrent will report its port setting to trackers/peers. So the port settings inside container should also be changed!

You can clone this repo, and then edit `port_range` (currently `45566-45566`) setting in `config/rtorrent/.rtorrent.rc` file. Then, build the modified image yourself.

**Comment by urbels** [comment]
ok thanks!
